### ISSUE TITLE
Field Match

### ISSUE THREAD

**Issue by tharrington** [ChicagoCityscape/api#1]
I am trying to locate the following keys for the API:

TOD Eligibility
TIF district
CHA Opportunity Zone (yes/no)

**Comment by stevevance** [comment]
Hey @tharrington I've updated the API to include TOD Eligibility and CHA opportunity zone in a new property called `incentives`. 

## TOD incentive

The TOD object will have many attributes because there are many rules to TOD. The main property you want to test for is the `likely` property. If `likely` is true, then you'll want to test if any of these are true:
- "parking" (you can take a parking reduction here)
- "density" (you can add more dwelling units than usual here)
- "height" (you can make your building taller than usual here)

These indicate which benefit or bonus the address is likely eligible for. 

You'll also want to look at `min_entrance_distance` and `proximal`. If `proximal` is true then you know the address is close to a train station entrance. `min_entrance_distance` tells you how far away it is, in feet. 

## Other incentives

In the CHA object, look for the `opp_area` attribute. This will say "yes" or "no". 

I've added two other properties, because they might be useful:
- `mmrp` - Micro Market Recovery Program
- `nof` - This location is in an area that's eligible to receive Neighborhood Opportunity Fund money
- `rtz` - Retail Thrive Zone: this location is an an area eligible to receive NOF money, and also in a targeted area for retail improvements
- `dte` - This location is an area outside the Downtown area, but is eligible to have its zoning classification changed to a "D" (downtown) zoning classification if the owner chooses and applies for it. 

All of these incentives are in arrays (except for TOD) because when you supply a PIN to the API, the API tests that parcel, and it's possible that the parcel spans multiple boundaries. 

## TIF districts
TIF districts are already included in the `boundaries` property, and if the address is in a TIF district, then the `boundaries` property will have a `tif` property which is an array of 1 or more elements (it should always have 1 element, though, because an address cannot be in more than 1 TIF district, but it's hypothetically possible that a *parcel* is in multiple TIF districts). 

## Sample
Here's a sample return showing the incentives. 
````
"incentives": {
            "cha": [
                {
                    "gid": 61,
                    "tract": "17031836800",
                    "namelsad10": "Census Tract 8368",
                    "gautreaux": "Limited",
                    "opp_area": "no"
                }
            ],
            "mmrp": [],
            "nof": [
                {
                    "gid": 47,
                    "tract": "17031836800",
                    "delmelleda": "Persistent Poverty",
                    "caname": "East Garfield Park"
                }
            ],
            "tod": {
                "likely": false,
                "parking": false,
                "density": false,
                "density_designation": null,
                "height": false,
                "trains_entrances": false,
                "special_residential": false,
                "min_entrance_distance": "878.48",
                "zone_classes": [],
                "zone_types": [],
                "zone_types_strings": [],
                "zone_pd_nums": [],
                "zone_types_names": [],
                "zone_type_string": [],
                "proximal": true
            },
            "rtz": [],
            "dte": [
                {
                    "gid": 1,
                    "intersects": true
                },
                {
                    "gid": 4,
                    "intersects": false
                },
                {
                    "gid": 3,
                    "intersects": false
                }
            ],
        },
````

And showing the TIF district:
````
"boundaries": {
            "communityarea": [
                {
                    "type": "communityarea",
                    "name": "East Garfield Park",
                    "metadata": "",
                    "slug": "communityarea-east-garfield-park"
                }
            ],
            "neighborhood": [
                {
                    "type": "neighborhood",
                    "name": "East Garfield Park",
                    "metadata": "",
                    "slug": "neighborhood-east-garfield-park"
                }
            ],
            "ward": [
                {
                    "type": "ward",
                    "name": "28th Ward, Alder Jason Ervin",
                    "metadata": "JASON ERVIN",
                    "slug": "ward-28"
                }
            ],
            "custom": [
                {
                    "type": "custom",
                    "name": "CTA stations - two blocks",
                    "metadata": "A single map of all CTA station entrances in Chicago.",
                    "slug": "custom-cta-stations-two-blocks"
                }
            ],
            "tif": [
                {
                    "type": "tif",
                    "name": "Chicago\/Central Park",
                    "metadata": "Mixed-use:  Residential\/Commercial|12\/31\/2026|2\/27\/2002",
                    "slug": "tif-chicago-central-park"
                }
            ],
````
